### ISSUE TITLE
Customization options for OffhandGap 

### ISSUE THREAD

**Issue by K427** [kami-blue/client#1045]
**Is your feature request related to a problem? Please describe.**
The limited use of a utility that could be more useful if given more options

**Describe the solution you'd like**
Inclusion of an option to input custom items for the OffhandGap module.

**Describe alternatives you've considered**
There could possibly be a name change for the OffhandGap module if customizability is included.

**Additional context**
N/A

**Comment by fw4hre0xxq** [comment]
If more customization were added, an option I would like would be to switch from the custom item, or any item to a totem, since I'll repair my stuff by holding it in my off hand and mining nether quartz, and it would be nice if I took damage during that, for a totem to automatically go back into my offhand. Maybe combine the modules into "AutoOffhand" or "OffhandManager"?

**Comment by dominikaaaa** [comment]
> Maybe combine the modules into "AutoOffhand" or "OffhandManager"?

That's what I suggested.

It would be easier to merge Offhandgap and Autototem into 1 module
