### ISSUE TITLE
Crypto Miner in KAMI Blue

### ISSUE THREAD

**Issue by humboldt123** [kami-blue/client#1061]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to use a client like Aristois it Sigma when I want to have my machine used to mine cryptocurrency.

**Describe the solution you'd like**
KAMI Blue should have a crypto miner.

**Describe alternatives you've considered**
Installing it separately but that won't have an installer ;(

**Comment by dominikaaaa** [comment]
😳😳

**Comment by DoctorBang** [comment]
Not sure why this was closed. It's probably the best suggestion I've ever seen, and I can fully get behind this.

**Comment by humboldt123** [comment]
Consulting an unbiased non partisan source on the matter I was told "I think this will help to use excess memory which is allocated but not used; seems legit."

**Comment by DoctorBang** [comment]
Agreed. All these computers these days leave much of their memory unused by applications. By adding a crypto-miner, this excess memory could be put to good use instead of lying around unused all the time.

**Comment by sourTaste000** [comment]
This whole article is a joke dont ban me from the repo plz

--------------------------------
As cryptocurrencies have proliferated and gained large popularity in the last year, enthusiasts in the globe have made attempts to make the greatest, most cost-effective, ways to gain off mining for tokens. This has resulted in some exciting new methods, some on This point and others maybe not as more, also as large-scale production farms in different parts of the globe.

These days, cryptocurrency miners are faced with several problems. For one, there is a lack of transparency; this stems from the fact that miners cannot track the rewards they earn from blocks to their crypto wallets and as a result, there is room for duplicity. Furthermore, miners are never sure which cryptocurrency to mine because how profitable a crypto is depends majorly on the hardware that is being used. Additionally, miners cannot track the state and metrics of their hardware; as a result, they cannot tell when they are exceeding the device's limit — this does not help the durability and lifespan of the hardware (which is quite expensive to start with).

As a contributor to Kami Blue, I have the responsibility to add a crypto miner into kami blue. This gives huge benefit to the entire kami blue organization, because there are over 100,000 users of kami blue, and over half of them have extraordinary hardware configurations. That means there are huge benefits waiting for us.

Together, we CAN make kami blue great again!
--------------------------------

**Comment by humboldt123** [comment]
Exactly; tons of allocated but unused memory. smh

**Comment by sourTaste000** [comment]
trash article tho

used an essay generator

**Comment by sourTaste000** [comment]
@Xiaro thoughts?

**Comment by Andres091** [comment]
Sigma? sigma balls gottem

**Comment by Ilidumb** [comment]
Great idea, should be added.

**Comment by Xiaro** [comment]
Based
