### ISSUE TITLE
CoordsLog with multiple instances of Minecraft

### ISSUE THREAD

**Issue by jumboman32** [kami-blue/client#1154]
The CoordsLog module is unable to record coordinates from multiple instances of Minecraft, even if one of the instances is not in-game. I died in-game and was unable to find my death coordinates due to another instance of Minecraft opened but in the main menu.

The Waypoints (Coords) file would work a lot better if it would have an account line at the top or above the server line.

I usually have two accounts up when I am playing (one AFK, one playing) and it would be nice if CoordsLog would work on both instances.

**Comment by dominikaaaa** [comment]
This isn't really possible. 

It's because when you closed the first instance of minecraft and then the second one, the second one overwrites the file with the information it has. 

This is because waypoints are loaded to memory when the game starts and then saved to disk whenever, in order to not destroy your disk and to improve performance. 

Instead you should be using multiple multimc profiles, as launching multiple instances inside the same folder *will* cause issues with not just kami blue, like the official MC launcher warns you
