### ISSUE TITLE
WaypointRender non-correct rendering outside of Render Distance

### ISSUE THREAD

**Issue by Finleyyy** [kami-blue/client#1198]
**Describe the bug**
WaypointRender only renders the ESP outside of the render distance when Camera isn't centered on the waypoint. The further you are the more you have to rotate the camera to see the ESP render again.

**To Reproduce**
1. Make a waypoint
2. Walk backwards until the ESP disappears
3. Rotate the camera a bit to show it again

**Expected behavior**
Always showing the waypoint if it's still in the set RenderRange.

**Screenshots**
https://imgur.com/a/K3RhNe5 

**Additional context**
My RenderRange was set to 4096.

**Comment by Xiaro** [comment]
Couldn't reproduce it on Vanilla KAMI Blue client (Forge + KAMI Blue only), probably caused by Optifine or other mods
![2020-08-28_22 30 53](https://user-images.githubusercontent.com/62033805/91626586-749fc400-e97e-11ea-85e3-bd945df647a6.png)
![2020-08-28_22 31 00](https://user-images.githubusercontent.com/62033805/91626587-75385a80-e97e-11ea-9842-8cad4e5de681.png)
![2020-08-28_22 31 04](https://user-images.githubusercontent.com/62033805/91626588-75d0f100-e97e-11ea-9010-dc8db77fe346.png)
![2020-08-28_22 31 06](https://user-images.githubusercontent.com/62033805/91626589-75d0f100-e97e-11ea-8772-470d19325781.png)
![2020-08-28_22 31 25](https://user-images.githubusercontent.com/62033805/91626590-75d0f100-e97e-11ea-9fa5-ceceacff4110.png)

**Comment by dominikaaaa** [comment]
Please reopen this if you can reproduce this without other mods
