### ISSUE TITLE
Easy profile switching 

### ISSUE THREAD

**Issue by Micro-Chan** [kami-blue/client#1217]
Make a GUI for loadingg configgs and saving/deletingg them. This will make loading different configs for different occasions much simpler.

**Comment by dominikaaaa** [comment]
An extension to the config command (eg `;config load`) would be a lot easier and would offer more customizability (eg macros)

All the command has to do is save config, edit KAMIBlueLastConfig.txt to the new file name and reload config 

The current GUI won't be updated feature wise because we're working on a new one. Maybe leave a comment on #790 if you want to see something similar on the new gui.
