### ISSUE TITLE
AntiBots

### ISSUE THREAD

**Issue by Slhsmile** [kami-blue/client#1271]
Some servers create fake entities / fake players around you to annoy you. Adding a feature to remove them would be cool

**Comment by Xiaro** [comment]
This was planned in Combat update 🤔

**Comment by RealIndrit** [comment]
this is unironically 3 lines of code you need to add 😳

**Comment by Nathan-Webb** [comment]
I thought stuff like this wasn't going to be added because its not really an anarchy server feature? I have never seen any anarchy server add bots to catch people using killaura. But tons of minigame servers use it. IIRC there was a conversation in the discord about how there wasn't going to be any minigame bypass modules because its out of project scope or smth.

**Comment by dominikaaaa** [comment]
That is correct. 

![Screenshot_20200830-113310.png](https://user-images.githubusercontent.com/17222512/91663076-98fdbc80-eab4-11ea-98af-ae656dd5861d.png)

**Comment by dominikaaaa** [comment]
I only kept this issue open because xiaro felt like doing it anyways.

**Comment by FluorideHistorian** [comment]
iirc 2b had bots when aac was first enabled

**Comment by Slhsmile** [comment]
> I only kept this issue open because xiaro felt like doing it anyways. In the future, I'll remove it from the main client and make it available as a plugin. 

I know that you are working not only on blue, can you recommend another cheat client that has an anti-cheat bypass module?

**Comment by dominikaaaa** [comment]
https://impactclient.net
