### ISSUE TITLE
Boss Stack wither names

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1638]
Created by: Muppet `(512003165416325120)`

An option in bosstack that reverts either names to 'Wither' on the client. I like seeing withers around me but don't like the hate speech.

**Comment by FriedrichM** [comment]
ill do this. 
For stack mode: 
do we want to keep the stack and have all of them say Boss or
do we want to have one stack named Boss with the sum of all stacks?

We don't differentiate between bosstypes, in vanilla there are only ender dragons and withers 
but servers can create a few more colored bossbars if they want. (see BossInfo.Color)

Because of this id suggest just putting them together to one bar named Boss that 
is colored the same as the closest boss's Bar would be colored when CensorNames is on.

**Comment by FriedrichM** [comment]
the BossBar objects dont contain any information about the boss type btw.

**Comment by l1ving** [comment]
> do we want to have one stack named Boss with the sum of all stacks

I think that's what they want, yes

**Comment by Xiaro** [comment]
Just count the boss from loaded entity. Display health for the closest one for each type.

**Comment by FriedrichM** [comment]
Bossbars can theoretically exist without entites.
If I just count bosses for each type in the loaded entities I will ignore the Bossbars which were added by server mods. 
The question is do we care for such servers as this is an anarchy client and extra Bossbars are more of a rpg-server thing?

If we do not care, I could create the Bossbars entirely from the loaded entities instead of from the SPacketUpdateBossInfo and thus also differentiate between bosstypes in the normal stack mode. 
(atm a ender dragon and a wither named the same will stack)

the alternative would be as mentioned above to have one stack named Boss with the sum of all stacks

**Comment by l1ving** [comment]
>  The question is do we care for such servers as this is an anarchy client and extra Bossbars are more of a rpg-server thing?

Just count them as bossbars lol.

>  (atm a ender dragon and a wither named the same will stack)

This is fine in my opinion. 
The way to go about implementing this is just stacking all boss bars, or separating withers and ender dragons, optionally.

**Comment by Xiaro** [comment]
> >  The question is do we care for such servers as this is an anarchy client and extra Bossbars are more of a rpg-server thing?
> 
> Just count them as bossbars lol.
> 
We are counting the entity :moyai:

**Comment by l1ving** [comment]
The entity might not exist

**Comment by Xiaro** [comment]
> The entity might not exist

That was his question. We will have to ignore those random ones if we count from entities. And counting from bossbar doesn't work because it doesn't contain the type of boss.

**Comment by FriedrichM** [comment]
Close pls
