### ISSUE TITLE
Ability to change the modlist that forge sends to the server

### ISSUE THREAD

**Issue by charlesathon** [kami-blue/client#1778]
I think it would be useful to have an undercover mode where KAMI isn't visible on forge client side modlists. Some servers require specific mods and check that you have them and only them before you can join the server. I'm not sure if it is even possible but I found a gitlab repo claiming to be able to do it but couldn't understand it and KAMI integration would be epic in my opinion.

https://gitlab.com/hexdiract/custom-forge-handshake

Also will there be 1.16.4 Forge compatability in the future?

**Comment by l1ving** [comment]
> Also will there be 1.16.4 Forge compatability in the future?

No, use KAMI.

Also, enable the FakeVanillaClient module

**Comment by iBuyMountainDew** [comment]
I dont think closing this was the right thing to do; he wants to send a customizable mod list, not pretend to be a vanilla client. This would work well as a plugin I reckon. Although something like this may cause some pretty serious bugs when playing on such servers. That's their problem.

**Comment by l1ving** [comment]
Our stance is if the server owner doesn't allow it, you shouldn't be doing it. I feel a module to do specifically this is against that philosophy and directly against the disclaimers we have on the website.

I've really only ever kept the FakeVanillaClient module because open to LAN testing sucks without it (Forge monke), and because the Forge KAMI had it.
