### ISSUE TITLE
ChunkFinder breaks StorageESP and HoleESP and Search [and AntiAFK in render branch]

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#474]
Similar to #463, it makes storage esp's esp completely opaque

**Comment by fw4hre0xxq** [comment]
I'm pretty sure this report was created because of a question I asked in discord, so I'll add info here.
Steps to Reproduce: Fresh install `Minecraft 1.12.2`, `Forge 14.23.5.2768`, and `KAMI-Blue-v1.1.2-release.jar`, turn on ChunkFinder and StorageESP at the same time, observe problem.

I tested this out on all the container types present in Minecraft 1.12.2. Here's what that looks like.

![2020-02-21_17 24 23](https://user-images.githubusercontent.com/60912178/75083646-34432300-54cf-11ea-9741-09336d4f6837.png)

**Comment by fw4hre0xxq** [comment]
Upon further testing, using ChunkFinder from Kami Blue, and the StorageESP from forgehax, that works. I think it's because forgehax's StorageESP only draws lines, not boxes. For now I'll use that as a workaround.

**Comment by S-B99** [comment]
It's because of how kami blue draws the storage esp, it's probably missing some open gl flags as in #463 
This has happened for a while.

**Comment by S-B99** [comment]
I've narrowed this down to the blend flags, maybe adding them to storage esp or removing them from chunkfinder will fix it.

**Comment by S-B99** [comment]
Moving milestone. Removing the blend seems to make it extremely transparent instead of opaque.

**Comment by zorftw** [comment]
The simple potential fix might be duplicating the current matrix and pushing an identical one on it, draw the ESP, and pop the matrix stack. This makes sure that whatever state you might've edited it will be restored to the original one after drawing.

**Comment by dominikaaaa** [comment]
I would've preferred to fix it in ChunkFinder because I feel that's the root cause, as the rest of those module's have clean rendering code, but I will look into that, thank you!

**Comment by dominikaaaa** [comment]
After some testing
- glEnable(GL_TEXTURE_2D); is what breaks the colors

**Comment by dominikaaaa** [comment]
and as expected, blending is what breaks the opacity

**Comment by dominikaaaa** [comment]
mostly fixed, for some reason it makes storageesp less transparent

**Comment by dominikaaaa** [comment]
got it
