### ISSUE TITLE
Baritone impl

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#584]
Blocked: waiting for #295, which is waiting for #521

See feature/baritoneImpl

**Comment by S-B99** [comment]
Before class-lookup was merged, I previously tried to use baritone. When opening a world it crashed at getModuleByName, which wasn't possible but it did. 

Now when you load a world it crashes with a configuration unsafe, which literally is no possible because KAMI's config is loaded on init, not when loading a world.  

Setup to install baritone: 

![2020-04-06-151844_1920x1080_scrot](https://user-images.githubusercontent.com/17222512/78596521-ee8db000-7819-11ea-9265-ce85b7cd353d.png)

I've decided not to implement baritone, which is extremely unfortunate but I don't see any other way to do this, other then having the user drop a BaritoneAPI jar in the mods folder and using that, which I can't even be sure won't crash as well, once I get past the difficulty of implementing that.

**Comment by dominikaaaa** [comment]
I'm reopening this to try and give it a shot with the API jar instead

**Comment by iBuyMountainDew** [comment]
Some major bruh moments may take place on merging due to the switch to kotlin; maybe keep the 'rewrites of each class in kotlin' branch local until this is merged?

**Comment by dominikaaaa** [comment]
That will only happen if you modify the same classes. I'm only converting *modules* to Kotlin.

**Comment by iBuyMountainDew** [comment]
too ez
