### ISSUE TITLE
Inventorymove breaks Future's autowalk

### ISSUE THREAD

**Issue by golfermatt** [kami-blue/client#677]
**What mod?**
Kami causes Future's autowalk to not work. It enables, but the player doesn't move.

**Logs**
Full log: https://pastebin.com/BLDv98aV
Probably the relevant part: https://pastebin.com/U9XX8KeD

**Additional context**
Looks like it's caused by inventory move's high mixin priority.
https://github.com/kami-blue/client/commit/94923cd86eea3541717ea3fbca40d4fd98bafdeb

**Comment by dominikaaaa** [comment]
It's completely intentional, because future had the bright idea of setting all of their mixins to max priority, so in order for my inventory move to work I need to set it to the max as well. Sucks for you if future's autowalk doesn't work (why do they need a mixin for that???) so just use kami blue's

**Comment by cookiedragon234** [comment]
Maybe ask @0-x-2-2 to not use 32 bit limit and actually care about client compatibility?

**Comment by dominikaaaa** [comment]
i talked to him in impact staff channel and his answer was a fat no

**Comment by iBuyMountainDew** [comment]
I think that the folks over at future do this to hamper compat on purpose, to try and encourage people to use only future with no other clients installed as supplements. Want a feature in another client? Either suck it up and use future only, waiting 6mo. for a new update, or deal with crippling bugs and problems. Your choice! @0-x-2-2

**Comment by 0-x-2-2** [comment]
> Maybe ask @0-x-2-2 to not use 32 bit limit and actually care about client compatibility?

https://github.com/kami-blue/client/issues/677#issuecomment-611745939

This will break things in both clients and it is a race condition otherwise of what hook will apply or not apply and if you want something to work with mixins when two people try to hook something don't use @Redirect or @Overwrite.

**Comment by dominikaaaa** [comment]
How do you propose I hook into MovementInputFromOptions to let you move around with GUIs open without a redirect?

**Comment by 0-x-2-2** [comment]
> How do you propose I hook into MovementInputFromOptions to let you move around with GUIs open without a redirect?

Is this why you hook it? wtf? this is a true useless hook compared to what Future uses it for.

**Comment by dominikaaaa** [comment]
It was a cleaner solution then manually listening to each key input and sending a move instruction when it's pressed.

**Comment by dominikaaaa** [comment]
>  someone can just use Futures inventory move instead so don't see the reason for you to make this thing.

some people don't have future, and I had the issue opened for a couple months and still got constant suggestions on the discord to add it, so clearly not everyone is using future.

**Comment by 0-x-2-2** [comment]
You should be avoiding such hooks when not necessary such a feature can be done without a hook by just using for-each. If you are not familar with that lingo here is someone explaining it: https://www.geeksforgeeks.org/for-each-loop-in-java/

**Comment by 0-x-2-2** [comment]
> some people don't have future, and I had the issue opened for a couple months and still got constant suggestions on the discord to add it, so clearly not everyone is using future.

This will only break with Future or possibly Impact and maybe ForgeHax so it is not a problem for those users because those clients already come with a fully-featured inventory move.

**Comment by 0-x-2-2** [comment]
> I think that the folks over at future do this to hamper compat on purpose

This is done to prevent users from needing to enable two or sometimes even 3 duplicated features in other clients like ViewClip and AntiFog or else they may get gl state leak issues causing black screens or even some features won't do anything at all due to unrelated hooks like this.

**Comment by dominikaaaa** [comment]
> This will only break with Future or possibly Impact and ForgeHax
Impact's inventorymove is broken on forge 1.12.2, as described by their github wiki, and it works fine with ForgeHax. 
> This is done to prevent users from needing to enable two or sometimes even 3 duplicated features like ViewClip and AntiFog
This is total user error and really you shouldn't be abusing a Mixin priority in order to "fix" it.

**Comment by dominikaaaa** [comment]
> such a feature can be done without a hook by just using for-each

As I described before, I'd rather not manually program each key and have it move when pressed, as Minecraft already does that for you but I guess that's the only solution here.

**Comment by 0-x-2-2** [comment]
> This is total user error

How is this a user error? This causes other unfixable actions in both clients and I would rather my client get picked over KAMI due to the bizarre crashes and render bugs with some features or features just not working at all.

> You shouldn't be abusing a Mixin priority in order to "fix" it.

You shouldn't be abusing `@Redirect` for things that can be done without a hook and another class. 

Mixin is fundamentally flawed and something gonna crash and burn hard when you have two things that depend on `@Redirect` because only one of them can hook it and not the other and that will is randomly picked unless you use the priority.

I can just as easily change the transformer to use a collection type that is guaranteed to keep the insert order and you would be in the same issue despite me not using Mixin priority aka the proper feature in Mixin for "solving" these issues because all this does is make everything consistent between launches and installs of the game and not some order from an objects hashCode.

**Comment by dominikaaaa** [comment]
It's user error because the user enabled features that do the same thing in different clients. I'd rather not manually do something that Minecraft already does but I guess that's the only solution here.

**Comment by 0-x-2-2** [comment]
https://github.com/kami-blue/client/pull/680#discussion_r407068120

**Comment by cookiedragon234** [comment]
🤡🤡🤡🤡🤡

The entire purpose of mixin is to allow bytecode modification compatible with multiple clients. Using 32bit limit goes against the purpose of mixin and is honestly just stupid. Not sure why anyone still uses future when the devs are so ignorant.

**Comment by 0-x-2-2** [comment]
> The entire purpose of mixin is to allow bytecode modification compatible with multiple clients. Using 32bit limit goes against the purpose of mixin and is honestly just stupid. Not sure why anyone still uses future when the devs are so ignorant.

How do you not understand how `@Redirect` works?

> Using 32bit limit goes against the purpose of mixin

This is just the inject order but please enlighten me how this goes against the purpose? Clearly you don't understand how this Mixin feature works perhaps?

**Comment by 0-x-2-2** [comment]
> The entire purpose of mixin is to allow bytecode modification compatible with multiple clients.

This is also not true at all and If this was true mixins would not have features like `@Redirect` and `@Overwrite` that by design are not compatible with any other transformers/mixins. Mixin is not anymore compatible or in-compatible then raw dog ASM, it is the developer's decision to make compatible hooks with other core mods. The purpose of Mixin is to make bytecode modification easier for the average person who wants to make easy and simple bytecode modifications without needing to understand the bytecode. 
https://github.com/SpongePowered/Mixin/issues/55#issuecomment-116599031
https://github.com/SpongePowered/Mixin/issues/11#issuecomment-69275850
https://github.com/SpongePowered/Mixin/issues/22#issuecomment-76624920

**Comment by Zamazenta** [comment]
tfw 0x22 knows how to properly use mixin and others don't so they blame their incompatibility on the person doing it right

**Comment by cookiedragon234** [comment]
> This is also not true at all and If this was true mixins would not have features like @Redirect and @Overwrite that by design are not compatible with any other transformers/mixins. Mixin is not anymore compatible or in-compatible then raw dog ASM, it is the developer's decision to make compatible hooks with other core mods.

Completely incorrect, from mixins wiki:
> Mixins are designed with awareness of other mixins in mind. Negotiation between mixins is provided by a simple priority system, a more complex companion plugin system, and by contract features such as the @Final annotation.
> All mixins provided by all consumers are applied to a particular target class in one pass, so that mixins interact with each other in predictable and ultimately deterministic ways.

**Comment by cookiedragon234** [comment]
> This is just the inject order but please enlighten me how this goes against the purpose? Clearly, you don't understand how this Mixin feature works perhaps? This only allows me to win the soft failing conflicts always with @Redirect and local var captures if I allow it to soft fail instead of it being determined by the internal collection used behavior.

When I say that using 32bit integer is against the purpose, what I mean is that the priority tag is given to us for a reason. It allows developers to say that one mixin is vital to the mod and should be prioritised over a mixin in another mod. By setting yours to the max value, you are implying that your mods mixins are more important than other mods mixins, which is almost certainly not the case.

Quoting wikis in an attempt to make your inconsiderate assumptions seem accurate or intelligent is not going to work.

**Comment by dominikaaaa** [comment]
> By setting yours to the max value, you are implying that your mods mixins are more important than other mods mixins, which is almost certainly not the case.

based

**Comment by 0-x-2-2** [comment]
None of my hooks are intended to fail soft and they either fail hard or they succeed there is nothing in the middle here because they will either crash or cause undefined behaviour and I am not creating conflict out of thin air because such conflict already existed and this preserves the behaviour I wanted and assume is gonna happen.

https://github.com/SpongePowered/Mixin/issues/52#issuecomment-110013473

> what I mean is that the priority tag is given to us for a reason

 I do not use the priority tag and I did not go out of my way for this such as manually by defining what will truly break super hard or not and what I did improved compatibility with much more popular forge mods so this will probably not change. I specified in my configuration to be the first to load for the same reason that I specified that my hooks are required and that is the behaviour that I wanted. 

Someone who truly cared about "client compatibility" would not use `@Redirect` at all because of true "client compatibility" would mean everything would work in both clients and that solution is simply not possible with Mixins `@Redirect`.

> you are implying that your mods mixins are more important than other mods mixins, which is almost certainly not the case.

This is very much the case I want my hooks to always be applied first and the only feature I use this will break with this is a `@Redirect` conflict that WILL break something no matter what anyways. All of my redirects are vital for my mod to function correctly and this is no different then KAMI bumping the priority to attempt to prevent me from winning these hooks. The only real solution for a `@Redirect` conflict is to change your hook.

> inconsiderate assumptions

This only stops accidental bugs with Future and anyone who would try to fix these conflicts properly can otherwise this would be broken anyways and there is nothing currently in place to prevent people to "fix" them improperly like Bella. This is no different functionally than me changing my load order other than the fact that they still have a say over it.

> actually care about client compatibility

This is correct I don't really care if someone can use KAMI with Future because not only does someone using another client stop or slow improvements of both clients via feature requests or other means, Future has multiple times more users using it fully standalone on 1.12.2 then KAMI or KAMI Blue but I still at least attempt to make sure everything in Future works and at least makes sure the game does not crash and does not get Future hooks overridden by KAMI aka literally the only mod I have found that has conflicting redirects with Future that cause major or noticeable issues even with 500+ mods mod packs.

What a coincidence that you are also guilty of doing this... https://github.com/SpongePowered/Mixin/issues/365#issuecomment-536953663

**Comment by leijurv** [comment]
proof that future is a top and kami blue is a bottom: this issue is filed on kami blue as kami blue breaking future, not the other way around. that tells you the priorities of the person who filed this issue 😹

**Comment by cookiedragon234** [comment]
> None of my hooks are intended to fail soft and they either fail hard or they succeed there is nothing in the middle here because they will either crash or cause undefined behaviour and I am not creating conflict out of thin air because such conflict already existed and this preserves the behaviour I wanted and assume is gonna happen.

Intending your mixins to fail hard is throwing any compatibility out of the window. If you really want that maybe use `required=1` instead of the priority tag.

It is a user problem to be combining clients, and by doing so they are accepting undefined behaviour.

> I do not use the priority tag and I did not go out of my way for this such as manually by defining what will truly break super hard or not and what I did improved compatibility with much more popular forge mods so this will probably not change. I specified in my configuration to be the first to load for the same reason that I specified that my hooks are required and that is the behaviour that I wanted.

According to @dominikaaaa the reason for this issue is that you use max value for your priority. You did not "improve compatibility" you simply blocked them from mixing into the same methods.

> This is very much the case I want my hooks to always be applied first and the only feature I use this will break with this is a @Redirect conflict that WILL break something no matter what anyways. All of my redirects are vital for my mod to function correctly and this is no different then KAMI bumping the priority to attempt to prevent me from winning these hooks. The only real solution for a @Redirect conflict is to change your hook.

These redirects are absolutely **vital** for your shitty block game cheat to allow inventory move lululul sure bro, there are plenty of ways to approach this problem

> This only stops accidental bugs with Future and anyone who would try to fix these conflicts properly can otherwise this would be broken anyways and there is nothing currently in place to prevent people to "fix" them improperly like Bella. This is no different functionally than me changing my load order other than the fact that they still have a say over it.

No one can "fix these conflicts" cause you blocked them out with 32bit limit priorities 😂 

> This is correct I don't really care if someone can use KAMI with Future

This is basically saying you dont care about probably 25% of your users at least

> Future has multiple times more users using it fully standalone

Ah yes more users due to fit bribes = better cheat

> What a coincidence that you are also guilty of doing this... SpongePowered/Mixin#365 (comment)

LOLOL seriously had to search through my github history just to shame me about an issue from 2019 rofl psure my priority was so high back then was to override your shitty mixins 😹. If we are looking to shame each other about when we were learning to code anyone can look through your history in impact discord lmao

**Comment by 0-x-2-2** [comment]
> LOLOL seriously had to search through my github history

No, I just found it today looking at the mixin repo with the "priority" keyword.

**Comment by dominikaaaa** [comment]
that was the only thing you decided to comment on? Nit picking for an argument much
