### ISSUE TITLE
Make speedometer accurate to more decimal places of precision.

### ISSUE THREAD

**Issue by ghost** [kami-blue/client#773]
**Is your feature request related to a problem? Please describe.**
I would like the speedometer feature to be more accurate.

**Describe the solution you'd like**
Instead of reading, for example, 5.6 m/s, infooverlay would show 5.6123345 m/s. Possibly configurable defaulting to 2 decimal places of precision?

edit: show not shout

**Comment by cookiedragon234** [comment]
**Is your feature request related to a problem? **Please describe.
I would like the speedometer feature to be more accurate.

**Describe the solution you'd like**
Instead of reading, for example, 5.6 m/s, infooverlay would shout 5.6123345 m/s. Possibly configurable defaulting to 2 decimal places of precision?

**Comment by golfermatt** [comment]
are you memeing my issue?

**Comment by dominikaaaa** [comment]
idk what cooker is doing tbh

**Comment by iBuyMountainDew** [comment]
He's just cookering yknow

**Comment by cookiedragon234** [comment]
https://www.google.com/amp/s/thinkingthroughourfingers.com/2016/03/22/style-tip-using-repetition-for-emphasis/amp/

**Comment by golfermatt** [comment]
eww amp link
