### ISSUE TITLE
Module idea

### ISSUE THREAD

**Issue by Tux8068** [kami-blue/client#877]
I would really like to see an "anti-coord-chat" module or something where it doesn't send the message if there's a + or a -, this will stop idiots from accidently leaking their bases or accidently messing up baritone.

**Comment by dominikaaaa** [comment]
I mean, most people don't actually include the +- when typing coords. 

This wouldn't be very useful because it won't prevent idiots from typing their coords out. 

Baritone has an option to hide coords in chat itself, and the chat is outlined when typing commands so you know it's not gonna be leaked.
